# Generated by Django 2.1 on 2021-08-22 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 10, 17, 58, 716140, tzinfo=utc)),
        ),
    ]
